// 人生五个阶段的愿望数据，每个阶段20个愿望，共100个
export const stages = [
    {
        id: 0,
        title: '童年时光',
        subtitle: '0-12岁 · 纯真与梦想的起点',
        description: '在这个无忧无虑的年纪，一切皆有可能',
        color: '#fbbf24',
        wishes: [
            { id: 'c01', emoji: '🏠', text: '在温暖的家庭中长大' },
            { id: 'c02', emoji: '🐕', text: '拥有一只忠诚的宠物' },
            { id: 'c03', emoji: '🎹', text: '学会一种乐器' },
            { id: 'c04', emoji: '🎨', text: '拥有绘画天赋' },
            { id: 'c05', emoji: '⚽', text: '成为运动健将' },
            { id: 'c06', emoji: '📚', text: '热爱阅读的习惯' },
            { id: 'c07', emoji: '👫', text: '拥有一群好朋友' },
            { id: 'c08', emoji: '🌳', text: '在大自然中自由奔跑' },
            { id: 'c09', emoji: '🎮', text: '无忧无虑地玩耍' },
            { id: 'c10', emoji: '✈️', text: '跟家人一起旅行' },
            { id: 'c11', emoji: '🎂', text: '每年都有热闹的生日派对' },
            { id: 'c12', emoji: '🏊', text: '学会游泳' },
            { id: 'c13', emoji: '🌟', text: '被老师表扬和认可' },
            { id: 'c14', emoji: '🎪', text: '去游乐园尽情玩耍' },
            { id: 'c15', emoji: '🍦', text: '吃遍各种美味零食' },
            { id: 'c16', emoji: '🚲', text: '学会骑自行车' },
            { id: 'c17', emoji: '🦸', text: '拥有超级英雄的梦想' },
            { id: 'c18', emoji: '🎄', text: '每个节日都充满惊喜' },
            { id: 'c19', emoji: '👨‍👩‍👧‍👦', text: '有兄弟姐妹陪伴' },
            { id: 'c20', emoji: '🌈', text: '保持对世界的好奇心' }
        ]
    },
    {
        id: 1,
        title: '青春年华',
        subtitle: '13-22岁 · 热血与迷茫交织',
        description: '在这个充满激情的年纪，你开始寻找自我',
        color: '#34d399',
        wishes: [
            { id: 'y01', emoji: '🎓', text: '考上理想的大学' },
            { id: 'y02', emoji: '💕', text: '经历一段纯真的初恋' },
            { id: 'y03', emoji: '🏆', text: '在竞赛中获得大奖' },
            { id: 'y04', emoji: '🎸', text: '组建一支乐队' },
            { id: 'y05', emoji: '📝', text: '写出一篇满分作文' },
            { id: 'y06', emoji: '🌍', text: '独自出国留学' },
            { id: 'y07', emoji: '💪', text: '拥有健美的身材' },
            { id: 'y08', emoji: '🎭', text: '参加话剧或社团表演' },
            { id: 'y09', emoji: '📱', text: '拥有自己的第一部手机' },
            { id: 'y10', emoji: '🏀', text: '在校队打比赛' },
            { id: 'y11', emoji: '✍️', text: '发表自己的第一篇文章' },
            { id: 'y12', emoji: '🎤', text: '在舞台上自信地演讲' },
            { id: 'y13', emoji: '🧪', text: '发现自己真正的兴趣' },
            { id: 'y14', emoji: '🚗', text: '拿到驾照' },
            { id: 'y15', emoji: '🏕️', text: '和朋友一起露营冒险' },
            { id: 'y16', emoji: '💻', text: '学会编程' },
            { id: 'y17', emoji: '🎵', text: '创作一首自己的歌' },
            { id: 'y18', emoji: '📸', text: '记录下青春的每个瞬间' },
            { id: 'y19', emoji: '🤝', text: '结交一生的挚友' },
            { id: 'y20', emoji: '🔥', text: '找到人生的方向和热情' }
        ]
    },
    {
        id: 2,
        title: '而立之年',
        subtitle: '23-35岁 · 拼搏与抉择的十字路口',
        description: '在这个关键的年纪，每个选择都影响深远',
        color: '#60a5fa',
        wishes: [
            { id: 'a01', emoji: '💼', text: '找到理想的工作' },
            { id: 'a02', emoji: '💍', text: '遇到灵魂伴侣并结婚' },
            { id: 'a03', emoji: '🏡', text: '买下属于自己的房子' },
            { id: 'a04', emoji: '🚀', text: '创业成功' },
            { id: 'a05', emoji: '💰', text: '实现财务自由' },
            { id: 'a06', emoji: '👶', text: '迎接第一个孩子' },
            { id: 'a07', emoji: '🌏', text: '环游世界' },
            { id: 'a08', emoji: '📖', text: '出版一本自己的书' },
            { id: 'a09', emoji: '🏋️', text: '保持健康的生活方式' },
            { id: 'a10', emoji: '🎯', text: '在行业内成为专家' },
            { id: 'a11', emoji: '🏎️', text: '拥有一辆梦想中的车' },
            { id: 'a12', emoji: '🐱', text: '养一只可爱的猫咪' },
            { id: 'a13', emoji: '🎓', text: '攻读硕士或博士学位' },
            { id: 'a14', emoji: '🏢', text: '升职成为管理层' },
            { id: 'a15', emoji: '🎻', text: '培养一个高雅的爱好' },
            { id: 'a16', emoji: '🤲', text: '参与公益慈善事业' },
            { id: 'a17', emoji: '🏠', text: '为父母买一套房' },
            { id: 'a18', emoji: '📈', text: '投资理财获得回报' },
            { id: 'a19', emoji: '🧘', text: '学会冥想和内心平静' },
            { id: 'a20', emoji: '🌟', text: '获得行业认可的奖项' }
        ]
    },
    {
        id: 3,
        title: '不惑之年',
        subtitle: '36-55岁 · 沉淀与收获的季节',
        description: '在这个成熟的年纪，你开始理解生活的真谛',
        color: '#f472b6',
        wishes: [
            { id: 'm01', emoji: '👨‍👩‍👧‍👦', text: '家庭和睦幸福' },
            { id: 'm02', emoji: '🏫', text: '看着孩子健康成长' },
            { id: 'm03', emoji: '💎', text: '事业达到巅峰' },
            { id: 'm04', emoji: '🏖️', text: '每年至少一次家庭旅行' },
            { id: 'm05', emoji: '🎨', text: '重拾年轻时的爱好' },
            { id: 'm06', emoji: '🏘️', text: '拥有一栋别墅' },
            { id: 'm07', emoji: '📚', text: '成为孩子的好榜样' },
            { id: 'm08', emoji: '💝', text: '与伴侣保持浪漫' },
            { id: 'm09', emoji: '🌿', text: '拥有自己的花园' },
            { id: 'm10', emoji: '🎓', text: '培养孩子考上好大学' },
            { id: 'm11', emoji: '🏥', text: '身体依然健康强壮' },
            { id: 'm12', emoji: '📝', text: '写下人生回忆录' },
            { id: 'm13', emoji: '🤝', text: '成为值得信赖的导师' },
            { id: 'm14', emoji: '🍷', text: '学会品味生活' },
            { id: 'm15', emoji: '🎭', text: '培养丰富的精神世界' },
            { id: 'm16', emoji: '💰', text: '为退休做好充足准备' },
            { id: 'm17', emoji: '🌍', text: '对社会做出贡献' },
            { id: 'm18', emoji: '🧠', text: '保持学习和成长' },
            { id: 'm19', emoji: '❤️', text: '与老朋友保持联系' },
            { id: 'm20', emoji: '🙏', text: '学会感恩和知足' }
        ]
    },
    {
        id: 4,
        title: '花甲之年',
        subtitle: '56岁以后 · 智慧与从容的黄昏',
        description: '在这个通透的年纪，你终于明白什么最重要',
        color: '#a78bfa',
        wishes: [
            { id: 'e01', emoji: '🏡', text: '在喜欢的城市安度晚年' },
            { id: 'e02', emoji: '👴👵', text: '与老伴相守到白头' },
            { id: 'e03', emoji: '👶', text: '享受含饴弄孙的乐趣' },
            { id: 'e04', emoji: '🌅', text: '每天看日出日落' },
            { id: 'e05', emoji: '✈️', text: '完成未完成的旅行清单' },
            { id: 'e06', emoji: '📖', text: '有读不完的好书' },
            { id: 'e07', emoji: '🎣', text: '过上悠闲的田园生活' },
            { id: 'e08', emoji: '💃', text: '保持活力和热情' },
            { id: 'e09', emoji: '🏥', text: '身体健康无大病' },
            { id: 'e10', emoji: '🎶', text: '每天都有音乐相伴' },
            { id: 'e11', emoji: '👨‍👩‍👧‍👦', text: '子女孝顺常回家' },
            { id: 'e12', emoji: '🌸', text: '种满鲜花的小院子' },
            { id: 'e13', emoji: '📷', text: '整理一生的照片回忆' },
            { id: 'e14', emoji: '🤝', text: '有一群老友常聚会' },
            { id: 'e15', emoji: '🎨', text: '学习书法或绘画' },
            { id: 'e16', emoji: '🧘', text: '内心平静无遗憾' },
            { id: 'e17', emoji: '💌', text: '给后人留下人生智慧' },
            { id: 'e18', emoji: '🌳', text: '种一棵能传承的树' },
            { id: 'e19', emoji: '😊', text: '回首往事无怨无悔' },
            { id: 'e20', emoji: '⭐', text: '被人记住和怀念' }
        ]
    }
];

// 结果页面的感悟语句
export const lifeQuotes = [
    '人生就像一盒巧克力，你永远不知道下一颗是什么味道。但正是这些未知，让旅程变得珍贵。',
    '我们无法拥有一切，但我们拥有的，已经是最好的选择。每一次放弃，都是为了更好的拥有。',
    '生命的意义不在于你得到了多少，而在于你选择了什么。那些消失的愿望，也是你人生故事的一部分。',
    '人生没有完美的剧本，但每一个选择都写就了独一无二的你。珍惜你所拥有的，释怀你所失去的。',
    '当你选择了一条路，就意味着放弃了另一条。但请相信，你走过的每一步，都有它的意义。'
];
